import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import AdminLayout from "./admin/components/AuthLayout";
import Productnav from "./components/navbar/ProductNav";
import Header1 from "./components/prevLoader";
import Mainnav from "./components/navbar/mainnav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "600"], // You can include multiple weights if needed
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["400"], // Add "600" if you need it too
});

export const metadata: Metadata = {
  title: "The drott",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />

        {children}
      </body>
    </html>
  );
}
